# Шаг 2.1: Даём имя нашему процессу (видно в интерфейсе)
name: Auto Deploy App

# Шаг 2.2: Говорим, КОГДА запускать процесс
on:
  push:
    branches: [ main ]  # Запускать ТОЛЬКО при пуше в ветку main

# Шаг 2.3: Что именно должен делать наш робот (основная работа)
jobs:
  deploy-job:  # Называем нашу задачу (можете любое имя)
    # Шаг 2.4: Где работать? Выбираем виртуальную машину
    runs-on: ubuntu-latest  # Самый популярный вариант
    
    # Шаг 2.5: Последовательность действий (шаги)
    steps:
      # Шаг 2.6: Скачать код из репозитория
      - name: Download Code
        uses: actions/checkout@v4  # Это как "git clone" для CI
        
      # Шаг 2.7: Запускаем ваш скрипт деплоя
      - name: Run Deploy Script
        run: |  # Здесь пишем команды для терминала
          echo "🚀 Начинаю процесс деплоя..."
          # Даём скрипту права на выполнение (если он есть)
          chmod +x deploy.sh
          # Запускаем ваш скрипт
          ./deploy.sh
          echo "✅ Деплой успешно завершён!"
          
      # Шаг 2.8: Создаём отчёт (дополнительно)
      - name: Create Report
        run: |
          echo "# Отчёт о деплое" > report.md
          echo "- Дата: $(date)" >> report.md
          echo "- Коммит: ${{ github.sha }}" >> report.md
          echo "- Пользователь: ${{ github.actor }}" >> report.md
          
      # Шаг 2.9: Сохраняем отчёт как артефакт
      - name: Save Report
        uses: actions/upload-artifact@v3
        with:
          name: deployment-report  # Имя файла
          path: report.md  # Что сохраняем
