name: Auto Deploy App

on:
  push:
    branches: [ main ]

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    
    steps:
      # Шаг 1: Скачиваем код (как git clone)
      - name: Download Code
        uses: actions/checkout@v4
        
      # Шаг 2: Запускаем наш скрипт деплоя
      - name: Run Deploy Script
        run: |
          echo "🚀 Запускаю скрипт деплоя..."
          # Даем права на запуск скрипта
          if [ -f "deploy.sh" ]; then
            chmod +x deploy.sh
            ./deploy.sh
          else
            echo "⚠️ Внимание: файл deploy.sh не найден!"
            echo "Создаю тестовый файл вместо скрипта..."
            touch test_file.txt
          fi
          echo "✅ Скрипт выполнен!"
          
      # Шаг 3: Создаем отчет
      - name: Create Report
        run: |
          echo "# Отчет о деплое" > report.md
          echo "- Дата: $(date)" >> report.md
          echo "- Коммит: ${{ github.sha }}" >> report.md
          echo "- Пользователь: ${{ github.actor }}" >> report.md
          echo "- Статус: Успешно!" >> report.md
          
      # Шаг 4: Сохраняем отчет (ИСПРАВЛЕННАЯ ВЕРСИЯ)
      - name: Save Report
        uses: actions/upload-artifact@v4  # ← ВОТ ТУТ ИСПРАВЛЕНИЕ!
        with:
          name: deployment-report
          path: report.md

      - name: Upload File List
        uses: actions/upload-artifact@v4
        with:
          name: file-list
          path: file-list.txt
